[2024-05-09T19:44:45.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T19:44:45.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-05-09T19:44:45.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-05-09T19:44:45.203+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-09T19:44:45.328+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): Notificar_Equipo> on 2024-01-01 00:00:00+00:00
[2024-05-09T19:44:45.335+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=926) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T19:44:45.336+0000] {standard_task_runner.py:63} INFO - Started process 928 to run task
[2024-05-09T19:44:45.336+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX', 'Notificar_Equipo', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '953', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX.py', '--cfg-path', '/tmp/tmp1mzyzu5m']
[2024-05-09T19:44:45.338+0000] {standard_task_runner.py:91} INFO - Job 953: Subtask Notificar_Equipo
[2024-05-09T19:44:45.384+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-01-01T00:00:00+00:00 [running]> on host 7a81a983afb0
[2024-05-09T19:44:45.442+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX' AIRFLOW_CTX_TASK_ID='Notificar_Equipo' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-05-09T19:44:45.451+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T19:44:45.471+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-09T19:44:45.479+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-09T19:44:45.513+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-09T19:44:45.517+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T19:44:45.518+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-05-09T19:44:45.536+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Proyecto_SpaceX, task_id=Notificar_Equipo, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240509T194445, end_date=20240509T194445
[2024-05-09T19:44:45.553+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 953 for task Notificar_Equipo ([Errno 99] Cannot assign requested address; 928)
[2024-05-09T19:44:45.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T19:44:45.611+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T19:44:45.614+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-10T05:21:25.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T05:21:25.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-05-10T05:21:25.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-05-10T05:21:25.597+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-10T05:21:25.762+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): Notificar_Equipo> on 2024-01-01 00:00:00+00:00
[2024-05-10T05:21:25.770+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T05:21:25.772+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX', 'Notificar_Equipo', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '1027', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX.py', '--cfg-path', '/tmp/tmpyj9jg7ne']
[2024-05-10T05:21:25.794+0000] {standard_task_runner.py:63} INFO - Started process 154 to run task
[2024-05-10T05:21:25.798+0000] {standard_task_runner.py:91} INFO - Job 1027: Subtask Notificar_Equipo
[2024-05-10T05:21:25.901+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-01-01T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T05:21:26.064+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX' AIRFLOW_CTX_TASK_ID='Notificar_Equipo' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-05-10T05:21:26.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T05:21:26.094+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-10T05:21:26.095+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-10T05:21:26.096+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-10T05:21:26.121+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T05:21:26.123+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-05-10T05:21:26.142+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Proyecto_SpaceX, task_id=Notificar_Equipo, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240510T052125, end_date=20240510T052126
[2024-05-10T05:21:26.326+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1027 for task Notificar_Equipo ([Errno 99] Cannot assign requested address; 154)
[2024-05-10T05:21:26.340+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T05:21:26.373+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T05:21:26.423+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
