[2024-05-08T21:09:31.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T21:09:31.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 9_XCom.tarea3 scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2024-05-08T21:09:31.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 9_XCom.tarea3 scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2024-05-08T21:09:31.397+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-08T21:09:31.426+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): tarea3> on 2022-01-01 00:00:00+00:00
[2024-05-08T21:09:31.432+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3623) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T21:09:31.433+0000] {standard_task_runner.py:63} INFO - Started process 3624 to run task
[2024-05-08T21:09:31.433+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '9_XCom', 'tarea3', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '848', '--raw', '--subdir', 'DAGS_FOLDER/09_XCom.py', '--cfg-path', '/tmp/tmp5x4b7kph']
[2024-05-08T21:09:31.434+0000] {standard_task_runner.py:91} INFO - Job 848: Subtask tarea3
[2024-05-08T21:09:31.469+0000] {task_command.py:426} INFO - Running <TaskInstance: 9_XCom.tarea3 scheduled__2022-01-01T00:00:00+00:00 [running]> on host ccc314eb571d
[2024-05-08T21:09:31.521+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='9_XCom' AIRFLOW_CTX_TASK_ID='tarea3' AIRFLOW_CTX_EXECUTION_DATE='2022-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-01-01T00:00:00+00:00'
[2024-05-08T21:09:31.522+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T21:09:31.531+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T21:09:31.532+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/09_XCom.py", line 9, in myfunction
    print(int(context["ti"].xcom_pull(task_ids='tarea2')) - 24)
              ^^^^^^^
NameError: name 'context' is not defined
[2024-05-08T21:09:31.542+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=9_XCom, task_id=tarea3, run_id=scheduled__2022-01-01T00:00:00+00:00, execution_date=20220101T000000, start_date=20240508T210931, end_date=20240508T210931
[2024-05-08T21:09:31.551+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 848 for task tarea3 (name 'context' is not defined; 3624)
[2024-05-08T21:09:31.567+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-08T21:09:31.577+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-08T21:09:31.580+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
