[2024-05-08T19:42:45.345+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T19:42:45.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3_filesensor.creating_file scheduled__2022-06-08T00:00:00+00:00 [queued]>
[2024-05-08T19:42:45.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3_filesensor.creating_file scheduled__2022-06-08T00:00:00+00:00 [queued]>
[2024-05-08T19:42:45.367+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-08T19:42:45.376+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): creating_file> on 2022-06-08 00:00:00+00:00
[2024-05-08T19:42:45.380+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1811) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T19:42:45.382+0000] {standard_task_runner.py:63} INFO - Started process 1812 to run task
[2024-05-08T19:42:45.382+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '7.3_filesensor', 'creating_file', 'scheduled__2022-06-08T00:00:00+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/07_FileSensor.py', '--cfg-path', '/tmp/tmphwfolp5x']
[2024-05-08T19:42:45.383+0000] {standard_task_runner.py:91} INFO - Job 622: Subtask creating_file
[2024-05-08T19:42:45.428+0000] {task_command.py:426} INFO - Running <TaskInstance: 7.3_filesensor.creating_file scheduled__2022-06-08T00:00:00+00:00 [running]> on host ccc314eb571d
[2024-05-08T19:42:45.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3_filesensor' AIRFLOW_CTX_TASK_ID='creating_file' AIRFLOW_CTX_EXECUTION_DATE='2022-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-08T00:00:00+00:00'
[2024-05-08T19:42:45.494+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T19:42:45.503+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-08T19:42:45.504+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 10 && touch /tmp/file.txt'"]
[2024-05-08T19:42:45.511+0000] {subprocess.py:86} INFO - Output:
[2024-05-08T19:42:45.512+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2024-05-08T19:42:45.512+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-08T19:42:45.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T19:42:45.520+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-08T19:42:45.523+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=7.3_filesensor, task_id=creating_file, run_id=scheduled__2022-06-08T00:00:00+00:00, execution_date=20220608T000000, start_date=20240508T194245, end_date=20240508T194245
[2024-05-08T19:42:45.532+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 622 for task creating_file (Bash command failed. The command returned a non-zero exit code 2.; 1812)
[2024-05-08T19:42:45.556+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-08T19:42:45.572+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-08T19:42:45.576+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
