[2024-05-09T20:01:47.761+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T20:01:47.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-05-09T20:01:47.785+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-05-09T20:01:47.789+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-09T20:01:47.911+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): Notificar_Equipo> on 2024-02-01 00:00:00+00:00
[2024-05-09T20:01:47.917+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1247) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T20:01:47.918+0000] {standard_task_runner.py:63} INFO - Started process 1249 to run task
[2024-05-09T20:01:47.918+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX', 'Notificar_Equipo', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '977', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX.py', '--cfg-path', '/tmp/tmpbprtpja2']
[2024-05-09T20:01:47.921+0000] {standard_task_runner.py:91} INFO - Job 977: Subtask Notificar_Equipo
[2024-05-09T20:01:47.993+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-02-01T00:00:00+00:00 [running]> on host 7a81a983afb0
[2024-05-09T20:01:48.066+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX' AIRFLOW_CTX_TASK_ID='Notificar_Equipo' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-05-09T20:01:48.071+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T20:01:48.088+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-09T20:01:48.092+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-09T20:01:48.102+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-09T20:01:48.107+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T20:01:48.110+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-05-09T20:01:48.125+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Proyecto_SpaceX, task_id=Notificar_Equipo, run_id=scheduled__2024-02-01T00:00:00+00:00, execution_date=20240201T000000, start_date=20240509T200147, end_date=20240509T200148
[2024-05-09T20:01:48.140+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 977 for task Notificar_Equipo ([Errno 99] Cannot assign requested address; 1249)
[2024-05-09T20:01:48.174+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T20:01:48.189+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T20:01:48.193+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-10T05:45:26.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T05:45:26.265+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-05-10T05:45:26.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-05-10T05:45:26.276+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-10T05:45:26.483+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): Notificar_Equipo> on 2024-02-01 00:00:00+00:00
[2024-05-10T05:45:26.492+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=558) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T05:45:26.495+0000] {standard_task_runner.py:63} INFO - Started process 560 to run task
[2024-05-10T05:45:26.494+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX', 'Notificar_Equipo', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '1051', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX.py', '--cfg-path', '/tmp/tmpk6oi18w0']
[2024-05-10T05:45:26.497+0000] {standard_task_runner.py:91} INFO - Job 1051: Subtask Notificar_Equipo
[2024-05-10T05:45:26.580+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-02-01T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T05:45:26.744+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX' AIRFLOW_CTX_TASK_ID='Notificar_Equipo' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-05-10T05:45:26.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T05:45:26.773+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-10T05:45:26.775+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-10T05:45:26.776+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-10T05:45:26.777+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T05:45:26.778+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-05-10T05:45:26.791+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Proyecto_SpaceX, task_id=Notificar_Equipo, run_id=scheduled__2024-02-01T00:00:00+00:00, execution_date=20240201T000000, start_date=20240510T054526, end_date=20240510T054526
[2024-05-10T05:45:26.805+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1051 for task Notificar_Equipo ([Errno 99] Cannot assign requested address; 560)
[2024-05-10T05:45:26.832+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T05:45:26.866+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T05:45:26.878+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
