[2024-05-08T19:50:42.644+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T19:50:42.662+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7.3_filesensor.waiting_file scheduled__2022-07-21T00:00:00+00:00 [queued]>
[2024-05-08T19:50:42.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7.3_filesensor.waiting_file scheduled__2022-07-21T00:00:00+00:00 [queued]>
[2024-05-08T19:50:42.671+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-08T19:50:42.683+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): waiting_file> on 2022-07-21 00:00:00+00:00
[2024-05-08T19:50:42.688+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T19:50:42.689+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '7.3_filesensor', 'waiting_file', 'scheduled__2022-07-21T00:00:00+00:00', '--job-id', '687', '--raw', '--subdir', 'DAGS_FOLDER/07_FileSensor.py', '--cfg-path', '/tmp/tmpjlxwxxtp']
[2024-05-08T19:50:42.692+0000] {standard_task_runner.py:63} INFO - Started process 2116 to run task
[2024-05-08T19:50:42.692+0000] {standard_task_runner.py:91} INFO - Job 687: Subtask waiting_file
[2024-05-08T19:50:42.732+0000] {task_command.py:426} INFO - Running <TaskInstance: 7.3_filesensor.waiting_file scheduled__2022-07-21T00:00:00+00:00 [running]> on host ccc314eb571d
[2024-05-08T19:50:42.791+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='7.3_filesensor' AIRFLOW_CTX_TASK_ID='waiting_file' AIRFLOW_CTX_EXECUTION_DATE='2022-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-21T00:00:00+00:00'
[2024-05-08T19:50:42.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T19:50:42.834+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-05-08T19:50:42.840+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T19:50:42.847+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 99, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 85, in poke
    self.log.info("Poking for file %s", self.path)
                                        ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 79, in path
    hook = FSHook(self.fs_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/filesystem.py", line 64, in __init__
    conn = self.get_connection(fs_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2024-05-08T19:50:42.851+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=7.3_filesensor, task_id=waiting_file, run_id=scheduled__2022-07-21T00:00:00+00:00, execution_date=20220721T000000, start_date=20240508T195042, end_date=20240508T195042
[2024-05-08T19:50:42.860+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 687 for task waiting_file (The conn_id `fs_default` isn't defined; 2116)
[2024-05-08T19:50:42.866+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-08T19:50:42.891+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-08T19:50:42.895+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
